import { AbiItem } from "web3-utils";

export const LoanAbi: AbiItem | AbiItem[] = [
  {
    inputs: [
      {
        internalType: "contract IUSDSynth",
        name: "_usdSynthToken",
        type: "address",
      },
      {
        internalType: "contract IPriceConsumerV3",
        name: "_price",
        type: "address",
      },
      {
        internalType: "contract IETHSynth",
        name: "_ethSynthToken",
        type: "address",
      },
      { internalType: "address", name: "_beyondExchange", type: "address" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    constant: true,
    inputs: [],
    name: "beyondExchange",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "_beneficiary", type: "address" },
    ],
    name: "closeLoan",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "_beneficiary", type: "address" },
    ],
    name: "closeLoanUSDb",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "uint256", name: "_value", type: "uint256" },
      { internalType: "address", name: "_beneficiary", type: "address" },
    ],
    name: "createLoan",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "uint256", name: "_value", type: "uint256" },
      { internalType: "address", name: "_beneficiary", type: "address" },
    ],
    name: "createLoanUSDb",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "ethSynthToken",
    outputs: [
      { internalType: "contract IETHSynth", name: "", type: "address" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "loanCollatteralRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "", type: "address" }],
    name: "loanDetails",
    outputs: [
      { internalType: "uint256", name: "collatteralETHb", type: "uint256" },
      { internalType: "uint256", name: "loanValueETHb", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalValueAfterLoanFeeETHb",
        type: "uint256",
      },
      { internalType: "uint256", name: "loansOfETHb", type: "uint256" },
      { internalType: "uint256", name: "collatteralUSDb", type: "uint256" },
      { internalType: "uint256", name: "loanValueUSDb", type: "uint256" },
      {
        internalType: "uint256",
        name: "totalValueAfterLoanFeeUSDb",
        type: "uint256",
      },
      { internalType: "uint256", name: "loansOfUSDb", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "loanFeeRatio",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "openLoans",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "price",
    outputs: [
      { internalType: "contract IPriceConsumerV3", name: "", type: "address" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "setBeyondExchangeAddress",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "uint256", name: "_collatteralRatio", type: "uint256" },
    ],
    name: "setLoanCollatteralRatio",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "_fee", type: "uint256" }],
    name: "setLoanFeeRation",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "string", name: "source", type: "string" }],
    name: "stringToBytes32",
    outputs: [{ internalType: "bytes32", name: "result", type: "bytes32" }],
    payable: false,
    stateMutability: "pure",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalETHb",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "totalUSDb",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "usdSynthToken",
    outputs: [
      { internalType: "contract IUSDSynth", name: "", type: "address" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "viewLoanConatractDetails",
    outputs: [
      { internalType: "uint256", name: "_loanFeeRatio", type: "uint256" },
      {
        internalType: "uint256",
        name: "_loanCollatteralRatio",
        type: "uint256",
      },
      { internalType: "uint256", name: "_totalETHb", type: "uint256" },
      { internalType: "uint256", name: "_totalUSDb", type: "uint256" },
      { internalType: "uint256", name: "_openLoans", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "viewLoanDetails",
    outputs: [
      { internalType: "uint256", name: "_collatteralETHb", type: "uint256" },
      { internalType: "uint256", name: "_loanValueETHb", type: "uint256" },
      {
        internalType: "uint256",
        name: "_totalValueAfterLoanFeeETHb",
        type: "uint256",
      },
      { internalType: "uint256", name: "_loansOfETHb", type: "uint256" },
      { internalType: "uint256", name: "_collatteralUSDb", type: "uint256" },
      { internalType: "uint256", name: "_loanValueUSDb", type: "uint256" },
      {
        internalType: "uint256",
        name: "_totalValueAfterLoanFeeUSDb",
        type: "uint256",
      },
      { internalType: "uint256", name: "_loansOfUSDb", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
