import { AbiItem } from "web3-utils";
export const PriceFeedAbi: AbiItem | AbiItem[] = [
  {
    inputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    constant: false,
    inputs: [{ internalType: "bytes32", name: "_synth", type: "bytes32" }],
    name: "getLatestPrice",
    outputs: [{ internalType: "int256", name: "", type: "int256" }],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "string", name: "_synth", type: "string" },
      {
        internalType: "contract IAggregatorV3Interface",
        name: "_address",
        type: "address",
      },
    ],
    name: "setSynthAddress",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "bytes32", name: "", type: "bytes32" }],
    name: "synthKey",
    outputs: [
      { internalType: "bytes32", name: "synth", type: "bytes32" },
      {
        internalType: "contract IAggregatorV3Interface",
        name: "priceFeedAddress",
        type: "address",
      },
      { internalType: "uint256", name: "_price", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "string", name: "_synth", type: "string" }],
    name: "viewLatestPrice",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
