import { AbiItem } from "web3-utils";
export const RewardAbi: AbiItem | AbiItem[] = [
  {
    inputs: [
      { internalType: "contract IBeyond", name: "_beyond", type: "address" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "constructor",
  },
  {
    anonymous: false,
    inputs: [
      {
        indexed: true,
        internalType: "address",
        name: "previousOwner",
        type: "address",
      },
      {
        indexed: true,
        internalType: "address",
        name: "newOwner",
        type: "address",
      },
    ],
    name: "OwnershipTransferred",
    type: "event",
  },
  {
    constant: true,
    inputs: [],
    name: "APY",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "beyond",
    outputs: [{ internalType: "contract IBeyond", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "beyondExProx",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "uint256", name: "beyondTokenValue", type: "uint256" },
      { internalType: "uint256", name: "bUSDValue", type: "uint256" },
      { internalType: "uint256", name: "totalMintedUSDb", type: "uint256" },
      { internalType: "uint256", name: "collatteralValue", type: "uint256" },
    ],
    name: "checkUserReward",
    outputs: [
      { internalType: "uint256", name: "reward", type: "uint256" },
      { internalType: "uint256", name: "tradeReward", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "address", name: "_beneficiary", type: "address" },
      { internalType: "uint256", name: "investTime", type: "uint256" },
      { internalType: "uint256", name: "_reward", type: "uint256" },
    ],
    name: "claimRewardFromReward",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [
      { internalType: "uint256", name: "beyondTokenValue", type: "uint256" },
      { internalType: "uint256", name: "bUSDValue", type: "uint256" },
      { internalType: "uint256", name: "totalMintedUSDb", type: "uint256" },
      { internalType: "uint256", name: "collatteralValue", type: "uint256" },
    ],
    name: "collectRewardFromReward",
    outputs: [
      { internalType: "uint256", name: "reward", type: "uint256" },
      { internalType: "uint256", name: "_rewardClaimTime", type: "uint256" },
      { internalType: "uint256", name: "currentCycleReward", type: "uint256" },
      { internalType: "uint256", name: "_currentTime", type: "uint256" },
    ],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "currentTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getRewardClaimTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "getRewardContractDetails",
    outputs: [
      { internalType: "uint256", name: "_currentTime", type: "uint256" },
      { internalType: "uint256", name: "_APY", type: "uint256" },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [],
    name: "initialize",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "interval",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "owner",
    outputs: [{ internalType: "address", name: "", type: "address" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [],
    name: "rewardClaimTime",
    outputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: true,
    inputs: [{ internalType: "uint256", name: "", type: "uint256" }],
    name: "rewardCycleDetail",
    outputs: [
      { internalType: "uint256", name: "currentCycleReward", type: "uint256" },
      { internalType: "uint256", name: "previousCycleReward", type: "uint256" },
      {
        internalType: "uint256",
        name: "cycleRewardRemaining",
        type: "uint256",
      },
    ],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "_APY", type: "uint256" }],
    name: "setAPY",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "_address", type: "address" }],
    name: "setExchangeProxAddress",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "address", name: "newOwner", type: "address" }],
    name: "transferOwnership",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: false,
    inputs: [{ internalType: "uint256", name: "_fee", type: "uint256" }],
    name: "updateReward",
    outputs: [],
    payable: false,
    stateMutability: "nonpayable",
    type: "function",
  },
  {
    constant: true,
    inputs: [
      { internalType: "uint256", name: "_time", type: "uint256" },
      { internalType: "uint256", name: "bUSDValue", type: "uint256" },
      { internalType: "uint256", name: "totalMintedUSDb", type: "uint256" },
    ],
    name: "userRewardDetailsFromReward",
    outputs: [{ internalType: "uint256", name: "_reward", type: "uint256" }],
    payable: false,
    stateMutability: "view",
    type: "function",
  },
];
